### PR TITLE
Add Docker file and fix book builder

### PR DESCRIPTION
**Pull request by LewMar**
Dzień dobry,
Dodałem Docker-a do łatwiejszego generowania książek.
Poprawiłem i uaktualniłem proces generowania książek, poprzez zaktualizowanie plików wspierając się o główny projekt [progit/progit2](https://github.com/progit/progit2), dodatkowo usunąłem generowanie książki w .mobi gdyż kindle zablokował taką możliwość.
Uaktualniłem README o informacje związane z poprawką jaką wprowadziłem.
Pozdrawiam LewMar

### CODE REVIEW

**Comment by KacperPerschke** [comment]
`kacper@zbigii:~/Robocze/Pro Git/Edition 2 PL$ docker-compose up`
`WARNING: The UID variable is not set. Defaulting to a blank string.`
`WARNING: The GID variable is not set. Defaulting to a blank string.`
`Creating network "edition2pl_default" with the default driver`
`Building book_build`
`Step 1/6 : FROM ruby:2.5`
`2.5: Pulling from library/ruby`
`0bc3020d05f1: Pull complete`
`a110e5871660: Pull complete`
`83d3c0fa203a: Pull complete`
`a8fd09c11b02: Pull complete`
`14feb89c4a52: Pull complete`
`958d2475f181: Pull complete`
`ba6c4f28fec1: Pull complete`
`757d13b54b5e: Pull complete`
`Digest: sha256:ecc3e4f5da13d881a415c9692bb52d2b85b090f38f4ad99ae94f932b3598444b`
`Status: Downloaded newer image for ruby:2.5`
` ---> 27d049ce98db`
`Step 2/6 : WORKDIR /usr/src/app`
` ---> Running in c6b34d75f5ca`
`Removing intermediate container c6b34d75f5ca`
` ---> cc8c9d8480b3`
`Step 3/6 : COPY Gemfile ./`
` ---> 5ef9b0231c27`
`Step 4/6 : RUN bundle install`
` ---> Running in 3eee67328523`
`Fetching gem metadata from https://rubygems.org/..........`
`Resolving dependencies...`
`Fetching rake 13.0.3`
`Installing rake 13.0.3`
`Fetching Ascii85 1.1.0`
`Installing Ascii85 1.1.0`
`Fetching public_suffix 4.0.6`
`Installing public_suffix 4.0.6`
`Fetching addressable 2.8.0`
`Installing addressable 2.8.0`
`Fetching afm 0.2.2`
`Installing afm 0.2.2`
`Fetching asciidoctor 2.0.12`
`Installing asciidoctor 2.0.12`
`Fetching mini_portile2 2.6.1`
`Installing mini_portile2 2.6.1`
`Fetching racc 1.5.2`
`Installing racc 1.5.2 with native extensions`
`Fetching nokogiri 1.12.5 (x86_64-linux)`
`Installing nokogiri 1.12.5 (x86_64-linux)`
`Fetching rubyzip 2.3.2`
`Installing rubyzip 2.3.2`
`Fetching gepub 1.0.15`
`Installing gepub 1.0.15`
`Fetching mime-types-data 3.2021.0901`
`Installing mime-types-data 3.2021.0901`
`Fetching mime-types 3.3.1`
`Installing mime-types 3.3.1`
`Fetching asciidoctor-epub3 1.5.0.alpha.19`
`Installing asciidoctor-epub3 1.5.0.alpha.19`
`Fetching concurrent-ruby 1.1.9`
`Installing concurrent-ruby 1.1.9`
`Fetching pdf-core 0.7.0`
`Installing pdf-core 0.7.0`
`Fetching ttfunk 1.5.1`
`Installing ttfunk 1.5.1`
`Fetching prawn 2.2.2`
`Installing prawn 2.2.2`
`Fetching prawn-icon 2.5.0`
`Installing prawn-icon 2.5.0`
`Fetching css_parser 1.10.0`
`Installing css_parser 1.10.0`
`Fetching prawn-svg 0.30.0`
`Installing prawn-svg 0.30.0`
`Fetching prawn-table 0.2.2`
`Installing prawn-table 0.2.2`
`Fetching hashery 2.1.2`
`Installing hashery 2.1.2`
`Fetching ruby-rc4 0.1.5`
`Installing ruby-rc4 0.1.5`
`Fetching pdf-reader 2.5.0`
`Installing pdf-reader 2.5.0`
`Fetching prawn-templates 0.1.2`
`Installing prawn-templates 0.1.2`
`Fetching safe_yaml 1.0.5`
`Installing safe_yaml 1.0.5`
`Fetching thread_safe 0.3.6`
`Installing thread_safe 0.3.6`
`Fetching polyglot 0.3.5`
`Installing polyglot 0.3.5`
`Fetching treetop 1.6.11`
`Installing treetop 1.6.11`
`Fetching asciidoctor-pdf 1.5.3`
`Installing asciidoctor-pdf 1.5.3`
`Fetching awesome_print 1.8.0`
`Installing awesome_print 1.8.0`
`Using bundler 1.17.3`
`Fetching coderay 1.1.3`
`Installing coderay 1.1.3`
`Fetching epubcheck-ruby 4.2.4.0`
`Installing epubcheck-ruby 4.2.4.0`
`Fetching ffi 1.15.4`
`Installing ffi 1.15.4 with native extensions`
`Fetching ethon 0.14.0`
`Installing ethon 0.14.0`
`Fetching mercenary 0.4.0`
`Installing mercenary 0.4.0`
`Fetching nokogumbo 2.0.5`
`Installing nokogumbo 2.0.5 with native extensions`
`Fetching parallel 1.21.0`
`Installing parallel 1.21.0`
`Fetching rainbow 3.0.0`
`Installing rainbow 3.0.0`
`Fetching typhoeus 1.4.0`
`Installing typhoeus 1.4.0`
`Fetching yell 2.2.2`
`Installing yell 2.2.2`
`Fetching html-proofer 3.18.2`
`Installing html-proofer 3.18.2`
`Fetching json 2.5.1`
`Installing json 2.5.1 with native extensions`
`Fetching multi_json 1.15.0`
`Installing multi_json 1.15.0`
`Fetching pygments.rb 1.2.1`
`Installing pygments.rb 1.2.1`
`Bundle complete! 11 Gemfile dependencies, 47 gems now installed.`
`Use `bundle info [gemname]` to see where a bundled gem is installed.`
`Post-install message from rubyzip:`
`RubyZip 3.0 is coming!`
`**********************`
``
`The public API of some Rubyzip classes has been modernized to use named`
`parameters for optional arguments. Please check your usage of the`
`following classes:`
`  * `Zip::File``
`  * `Zip::Entry``
`  * `Zip::InputStream``
`  * `Zip::OutputStream``
``
`Please ensure that your Gemfiles and .gemspecs are suitably restrictive`
`to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).`
`See https://github.com/rubyzip/rubyzip for details. The Changelog also`
`lists other enhancements and bugfixes that have been implemented since`
`version 2.3.0.`
`Removing intermediate container 3eee67328523`
` ---> d34b50421f29`
`Step 5/6 : COPY . .`
` ---> ec7d9021b26e`
`Step 6/6 : CMD ["bundle","exec","rake","book:build"]`
` ---> Running in d94de7f171d5`
`Removing intermediate container d94de7f171d5`
` ---> 34cf8da82268`
``
`Successfully built 34cf8da82268`
`Successfully tagged edition2pl_book_build:latest`
`WARNING: Image for service book_build was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.`
`Creating edition2pl_book_build_1 ... done`
`Attaching to edition2pl_book_build_1`
`book_build_1  | Bundler::GemNotFound: Could not find Ascii85-1.0.3 in any of the sources`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'`
`book_build_1  |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'`
`book_build_1  | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)`
`edition2pl_book_build_1 exited with code 1`
`

**Comment by LewMar** [comment]
Dzień dobry, 
zaktualizowałem ruby do 2.6 oraz zależności takie jak w progit/progit2

**Comment by KacperPerschke** [comment]
Marcinie
```
kacper@zbigii:~/Robocze/Pro Git/Edition 2 PL ((2fe935f...))$ git log -1
commit 2fe935ffe478ae7a2e5e5361845b0e7cdc278ef3 (HEAD, LewMar/add-docker-and-fix-book-builder)
Author: Lewandowski Marcin <lewandowski@marcin.cloud>
Date:   Sun Nov 7 14:33:35 2021 +0100

    Update to ruby:2.6
```

Teraz pozwolę sobie pokazać bez informacji, które wydają mi się nieistotne:
```
kacper@zbigii:~/Robocze/Pro Git/Edition 2 PL ((2fe935f...))$ docker-compose up
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
Building book_build
Step 1/6 : FROM ruby:2.6
2.6: Pulling from library/ruby
⋮
Successfully built 0fde21508a6c
Successfully tagged edition2pl_book_build:latest
WARNING: Image for service book_build was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating edition2pl_book_build_1 ... done
Attaching to edition2pl_book_build_1
book_build_1  | Bundler::GemNotFound: Could not find mime-types-data-3.2021.0901 in any of the sources
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/runtime.rb:20:in `setup'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler.rb:107:in `setup'
book_build_1  |   /usr/local/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
book_build_1  |   /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
book_build_1  |   /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
book_build_1  | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
edition2pl_book_build_1 exited with code 1
```
```
kacper@zbigii:~/Robocze/Pro Git/Edition 2 PL ((2fe935f...))$ docker image ls
REPOSITORY              TAG       IMAGE ID       CREATED          SIZE
edition2pl_book_build   latest    0fde21508a6c   10 minutes ago   1.19GB
ruby                    2.6       2bc264b900b4   38 hours ago     870MB
kacper@zbigii:~/Robocze/Pro Git/Edition 2 PL ((2fe935f...))$ docker run -it --entrypoint "/bin/bash" edition2pl_book_build 
root@cd175999880a:/usr/src/app# ls -l /usr/local/bundle/bin/rake 
-rwxr-xr-x 1 root root 514 Nov 19 13:20 /usr/local/bundle/bin/rake
root@cd175999880a:/usr/src/app# file /usr/local/bundle/bin/rake 
/usr/local/bundle/bin/rake: Ruby script, ASCII text executable
root@cd175999880a:/usr/src/app# id
uid=0(root) gid=0(root) groups=0(root)
root@cd175999880a:/usr/src/app# exit
```

Czy to są wystarczające informacje?

**Comment by lkord** [comment]
Conflicts to resolve

**Review by lkord — DISMISSED** [review]
Please resolve conflicts before merge

**Comment by davpal** [comment]
It should works with new Gemfile from master

**Comment by lkord** [comment]
> It should works with new Gemfile from master

If you are sure of this you merge it

**Comment by davpal** [comment]
@lkord Please check on your side that container is working. Just do the `docker-compose up`

**Review by davpal — APPROVED** [review]
@Ikord

**Comment by olsza** [comment]
> @lkord @olsza Please check on your side that container is working. Just do the `docker-compose up`

ok, I will check tonight and give a comment
ps. @davpal  I was generally to check this week ;)

**Comment by olsza** [comment]
@davpal I saw an early conflict that was resolved in this PR, but it seems to me that the wrong choice was made, because looking at https://github.com/progit2-pl/progit2-pl/pull/12/commits/8d1bc820b55d9dca140115921b65acab8de08378
older version files were selected in the `Gemfile`, and I think there should be newer ones.
But I am not good at this issue, so I could be wrong

**Comment by davpal** [comment]
> @davpal I saw an early conflict that was resolved in this PR, but it seems to me that the wrong choice was made, because looking at [8d1bc82](https://github.com/progit2-pl/progit2-pl/commit/8d1bc820b55d9dca140115921b65acab8de08378) older version files were selected in the `Gemfile`, and I think there should be newer ones. But I am not good at this issue, so I could be wrong

That's right. I just messed something with remotes, now Gemfile should match progit/main branch

**Comment by olsza** [comment]
All in good order :) :+1: 
It works - I added "Olsza - TEST" and it generated as below :D

image

**Review by olsza — APPROVED** [review]

**Comment by Toppole6** [comment]
> Dzień dobry,
> 
> Dodałem Docker-a do łatwiejszego generowania książek.
> 
> Poprawiłem i uaktualniłem proces generowania książek, poprzez zaktualizowanie plików wspierając się o główny projekt [progit/progit2](https://github.com/progit/progit2), dodatkowo usunąłem generowanie książki w .mobi gdyż kindle zablokował taką możliwość.
> 
> Uaktualniłem README o informacje związane z poprawką jaką wprowadziłem.
> 
> Pozdrawiam LewMar 

[](https://share.goodnotes.com/s/ICHgTzGb8joH76Jx5ClQV2)

**Review by Toppole6 — COMMENTED** [review]
``

**Pull request merged**
